### ISSUE TITLE
Issue with integration with pyarrow

### ISSUE THREAD

**Issue by srizvan** [intake/filesystem_spec#210] opened 2019-11-27 12:09 UTC
Env:
Python 3.7.4
fsspec==0.6.0
pyarrow==0.15.1
dask==2.8.1

When I'm trying to read data frame from HDFS, the next issue appears:
```
df = dd.read_csv('hdfs://hostname:9820/data/ds_*.csv')

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-368b0d249316> in <module>
----> 1 df = dd.read_csv('hdfs://hostname:9820/data/ds_*.csv')

~/miniconda3/lib/python3.7/site-packages/dask/dataframe/io/csv.py in read(urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    576             storage_options=storage_options,
    577             include_path_column=include_path_column,
--> 578             **kwargs
    579         )
    580 

~/miniconda3/lib/python3.7/site-packages/dask/dataframe/io/csv.py in read_pandas(reader, urlpath, blocksize, collection, lineterminator, compression, sample, enforce, assume_missing, storage_options, include_path_column, **kwargs)
    403         compression=compression,
    404         include_path=include_path_column,
--> 405         **(storage_options or {})
    406     )
    407 

~/miniconda3/lib/python3.7/site-packages/dask/bytes/core.py in read_bytes(urlpath, delimiter, not_zero, blocksize, sample, compression, include_path, **kwargs)
    156         if isinstance(sample, str):
    157             sample = parse_bytes(sample)
--> 158         with OpenFile(fs, paths[0], compression=compression) as f:
    159             # read block without seek (because we start at zero)
    160             if delimiter is None:

~/miniconda3/lib/python3.7/site-packages/fsspec/core.py in __enter__(self)
     96         mode = self.mode.replace("t", "").replace("b", "") + "b"
     97 
---> 98         f = self.fs.open(self.path, mode=mode)
     99 
    100         self.fobjects = [f]

~/miniconda3/lib/python3.7/site-packages/fsspec/implementations/hdfs.py in <lambda>(*args, **kw)
    116             # all the methods defined in this class. Note `open` here, since
    117             # it calls `_open`, but is actually in superclass
--> 118             return lambda *args, **kw: getattr(PyArrowHDFS, item)(self, *args, **kw)
    119         if item == "__class__":
    120             return PyArrowHDFS

~/miniconda3/lib/python3.7/site-packages/fsspec/spec.py in open(self, path, mode, block_size, cache_options, **kwargs)
    723                 autocommit=ac,
    724                 cache_options=cache_options,
--> 725                 **kwargs
    726             )
    727             if not ac:

~/miniconda3/lib/python3.7/site-packages/fsspec/implementations/hdfs.py in <lambda>(*args, **kw)
    116             # all the methods defined in this class. Note `open` here, since
    117             # it calls `_open`, but is actually in superclass
--> 118             return lambda *args, **kw: getattr(PyArrowHDFS, item)(self, *args, **kw)
    119         if item == "__class__":
    120             return PyArrowHDFS

~/miniconda3/lib/python3.7/site-packages/fsspec/implementations/hdfs.py in _open(self, path, mode, block_size, autocommit, **kwargs)
     72         if not autocommit:
     73             raise NotImplementedError
---> 74         return HDFSFile(self, path, mode, block_size, **kwargs)
     75 
     76     def __reduce_ex__(self, protocol):

~/miniconda3/lib/python3.7/site-packages/fsspec/implementations/hdfs.py in __init__(self, fs, path, mode, block_size, **kwargs)
    171         self.mode = mode
    172         self.block_size = block_size
--> 173         self.fh = fs.pahdfs.open(path, mode, block_size, **kwargs)
    174         if self.fh.readable():
    175             self.seek_size = self.size()

~/miniconda3/lib/python3.7/site-packages/pyarrow/io-hdfs.pxi in pyarrow.lib.HadoopFileSystem.open()

TypeError: open() got an unexpected keyword argument 'cache_options'
```

As a workaround, I just comment out line 724 in the ~/miniconda3/lib/python3.7/site-packages/fsspec/spec.py file (`cache_options=cache_options,`).

**Comment by jacobtomlinson** [comment] 2019-11-27 12:51
Thanks for raising this issue. Lots of folks are out for the holidays this week, so there may not be much response here until next week.

Looks like that line was added by @TomAugspurger in #195. @TomAugspurger do you have thoughts here?

**Comment by TomAugspurger** [comment] 2019-11-27 13:06
Already fixed in https://github.com/intake/filesystem_spec/pull/202 I think.

**Comment by jacobtomlinson** [comment] 2019-11-27 13:26
Ah great. This may be a duplicate of #198 then.

@srizvan this should be fixed in the next release. In the meantime you can install this project from source if you want to test out the fix `pip install git+https://github.com/intake/filesystem_spec.git`.

**Comment by TomAugspurger** [comment] 2019-11-27 14:23
I'll try to do a release today.

**Comment by TomAugspurger** [comment] 2019-11-27 19:14
fsspec 0.6.1 is out now. This should be fixed.

**Closed by TomAugspurger** 2019-11-27 19:14 UTC
